import {
  mysqlTable,
  mysqlEnum,
  serial,
  varchar,
  int,
  text,
  boolean,
  float,
  date,
  timestamp,
  primaryKey,
  datetime,
  index,
} from 'drizzle-orm/mysql-core';

export const tblPayments = mysqlTable(
  'tbl_payments',
  {
    paymentId: int('payment_id').autoincrement().notNull(),
    regId: int('reg_id').notNull(),
    programId: int('program_id').notNull(),
    batchId: int('batch_id'),
    paidFor: int('paid_for').notNull(),
    programName: varchar('program_name', { length: 100 }).notNull(),
    paymentOption: varchar('payment_option', { length: 50 }).notNull(),
    designation: varchar({ length: 50 }),
    payInstallment1: varchar('pay_installment_1', { length: 10 }),
    payInstallment2: varchar('pay_installment_2', { length: 10 }),
    payInstallment3: varchar('pay_installment_3', { length: 10 }),
    trackAccess: varchar('track_access', { length: 50 })
      .default('1,2,3')
      .notNull(),
    moduleViewtype: mysqlEnum('module_viewtype', ['1', '2']).notNull(),
    programAmount: varchar('program_amount', { length: 50 }).notNull(),
    couponCode: varchar('coupon_code', { length: 50 }),
    discountAmount: varchar('discount_amount', { length: 50 }),
    discountReferralAmount: varchar('discount_referral_amount', { length: 50 }),
    discountReferralPerson: varchar('discount_referral_person', { length: 50 }),
    referrerCode: varchar('referrer_code', { length: 10 }),
    redeemAmount: float('redeem_amount').notNull(),
    advanceAmount: float('advance_amount').notNull(),
    subtotalAmount: varchar('subtotal_amount', { length: 50 }).notNull(),
    taxAmount: varchar('tax_amount', { length: 50 }).notNull(),
    finalAmount: varchar('final_amount', { length: 50 }).notNull(),
    currency: varchar({ length: 10 }).notNull(),
    orderId: varchar('order_id', { length: 50 }).notNull(),
    orderStatus: varchar('order_status', { length: 50 }),
    paySession: varchar('pay_session', { length: 50 }).notNull(),
    pgEmail: varchar('pg_email', { length: 100 }),
    pgMobile: varchar('pg_mobile', { length: 50 }),
    pgCurrency: varchar('pg_currency', { length: 50 }),
    pgAmount: varchar('pg_amount', { length: 50 }),
    paymentEntry: varchar('payment_entry', { length: 50 }),
    paymentDate: date('payment_date', { mode: 'string' }),
    payId: varchar('pay_id', { length: 50 }),
    payStatus: varchar('pay_status', { length: 50 }),
    accessStatus: mysqlEnum('access_status', ['0', '1']).notNull(),
    invoiceNumber: int('invoice_number'),
    createdDate: timestamp('created_date', { mode: 'string' })
      .defaultNow()
      .notNull(),
    modifiedDate: datetime('modified_date', { mode: 'string' }),
    handsonId: varchar('handson_id', { length: 50 }),
    facultyIds: varchar('faculty_ids', { length: 255 }),
    scheduledDate: date('scheduled_date', { mode: 'string' }),
    timing: varchar({ length: 100 }),
  },
  (table) => [
    primaryKey({ columns: [table.paymentId], name: 'tbl_payments_payment_id' }),
    index('idx_user_status').on(table.regId, table.payStatus),
    index('idx_batch_id').on(table.batchId),
    index('idx_program_id').on(table.programId),
    index('idx_payment_date').on(table.paymentDate),
  ],
);
