import {
  mysqlTable,
  mysqlEnum,
  serial,
  varchar,
  int,
  text,
  boolean,
  longtext,
  datetime,
  date,
  time,
  timestamp,
  primaryKey,
} from 'drizzle-orm/mysql-core';

export const tblSessions = mysqlTable(
  'tbl_sessions',
  {
    sessionId: int('session_id').autoincrement().notNull(),
    programId: int('program_id'),
    batchId: int('batch_id'),
    phaseId: int('phase_id'),
    moduleId: int('module_id'),
    crsectionId: int('crsection_id'),
    programType: mysqlEnum('program_type', ['0', '1']).notNull(),
    sessionName: varchar('session_name', { length: 500 }).notNull(),
    facultyName: varchar('faculty_name', { length: 500 }),
    sessionDescription: longtext('session_description'),
    sessionImage: varchar('session_image', { length: 100 }).notNull(),
    sessionType: varchar('session_type', { length: 50 }).notNull(),
    sessionUrl: varchar('session_url', { length: 500 }).notNull(),
    isZoom: mysqlEnum('is_zoom', ['0', '1']).notNull(),
    zoomMeetingId: varchar('zoom_meeting_id', { length: 255 }),
    zoomStartdate: datetime('zoom_startdate', { mode: 'string' }),
    zoomEnddate: datetime('zoom_enddate', { mode: 'string' }),
    zoomPassword: varchar('zoom_password', { length: 20 }),
    zoomLiveLink: varchar('zoom_live_link', { length: 255 }),
    zoombackupStatus: mysqlEnum('zoombackup_status', ['0', '1']).notNull(),
    dicomVideoUrl: varchar('dicom_video_url', { length: 500 }),
    dicomCaseId: varchar('dicom_case_id', { length: 50 }),
    assessmentPassPercentage: int('assessment_pass_percentage').default(100),
    duration: varchar({ length: 100 }),
    startDate: date('start_date', { mode: 'string' }).notNull(),
    startTime: time('start_time').notNull(),
    startDatetime: datetime('start_datetime', { mode: 'string' }),
    endDate: date('end_date', { mode: 'string' }).notNull(),
    endTime: time('end_time').notNull(),
    endDatetime: datetime('end_datetime', { mode: 'string' }),
    videoStatus: mysqlEnum('video_status', ['Recorded', 'Live']).notNull(),
    lockStatus: mysqlEnum('lock_status', ['1', '0']).notNull(),
    sponsored: mysqlEnum(['1', '0']).notNull(),
    status: mysqlEnum(['1', '0']).notNull(),
    createdDate: timestamp('created_date', { mode: 'string' })
      .defaultNow()
      .notNull(),
    modifiedDate: datetime('modified_date', { mode: 'string' }),
  },
  (table) => [
    primaryKey({ columns: [table.sessionId], name: 'tbl_sessions_session_id' }),
  ],
);
